---
framework: mocha
preRun:
     command:
        - /usr/local/bin/bundle --ping
        - yarn install
preMerge:
  pattern:
    - "./node-tests/blueprints/**/*-test.js"
postMerge:
  pattern: 
    - "./node-tests/blueprints/**/*-test.js"
postRun:
     command:
        - yarn --version
version: 1.4

